Finish BuildWindows Github Action with CMake build and sanity check

diff --git a/.github/workflows/BuildWindows.yml b/.github/workflows/BuildWindows.yml
--- a/.github/workflows/BuildWindows.yml
+++ b/.github/workflows/BuildWindows.yml
@@ -11,23 +11,50 @@ jobs:
     runs-on: windows-latest
     steps:
 
-      - uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v3
         with:
           submodules: true
 
-      # Install latest CMake and Ninja.
-      - uses: lukka/get-cmake@latest
+      - name: Get latest CMake and Ninja
+        uses: lukka/get-cmake@latest
 
       - name: Get vcpkg
         uses: lukka/run-vcpkg@v11 
         with:
-          vcpkgDirectory: '${{ github.workspace }}/utilities/vcpkg'
-          vcpkgJsonGlob: 'vcpkg.json'
+          # this path is arbitrary:
+          vcpkgDirectory: '${{ github.workspace }}/_tools/vcpkg'
 
-      - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
+      - name: Get dependencies and configure the build with CMake
         uses: lukka/run-cmake@v10
         with:
           configurePreset: 'windows-clang'
+      
+      - name: Build project
+        run: cmake --build .
+      
+      - name: Check if built executable exists and is sane
+        shell: pwsh
+        run: |
+          cd bin
+          
+          # this is just for logging purposes:
+          dir
 
-env:
-  VCPKG_ROOT: '${{ github.workspace }}/utilities/vcpkg'
+          # checking that srcdiff actually runs is especially important on
+          # windows, since everything can succesfully build but still fail to
+          # dynamically link up at runtime
+          
+          # get version info output:
+          $version_info = ./srcdiff -V
+
+          Write-Output "Version info:"
+          Write-Output $version_info
+
+          # make sure the string "srcdiff" is somewhere in the version output
+          # this is case insensitive
+          if (($version_info -match "srcdiff").Length -eq 0){
+            exit 1
+          }
+
+          Write-Output "Build succeeded!"
